### ISSUE TITLE
PHP warnings when using plugin on PHP8.2

### ISSUE THREAD

**Issue by piotrbak** [wp-media/heartbeat-control#12]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are experiencing the following PHP errors on this specific version:
- [14-Aug-2023 09:04:14 UTC] PHP Warning:  Undefined variable $old_location in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/heartbeat-control.php on line 77
- [14-Aug-2023 09:04:14 UTC] PHP Warning:  Undefined array key "heartbeat_control_location" in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/heartbeat-control.php on line 129
- [14-Aug-2023 09:04:14 UTC] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/heartbeat-control.php on line 129
- [14-Aug-2023 09:04:15 UTC] PHP Deprecated:  Optional parameter $type declared before required parameter $field_id is implicitly treated as a required parameter in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/vendor/cmb2/cmb2/includes/rest-api/CMB2_REST.php on line 693
- [14-Aug-2023 09:05:16 UTC] PHP Deprecated:  Optional parameter $args declared before required parameter $i is implicitly treated as a required parameter in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/vendor/cmb2/cmb2/includes/types/CMB2_Type_Multi_Base.php on line 34
- [14-Aug-2023 09:05:48 UTC] PHP Warning:  Undefined array key "2x" in /var/www/rocketlabsqa.ovh/htdocs/wp-content/plugins/heartbeat-control/Plugin_Card_Helper.php on line 244

**To Reproduce**
1. Use PHP8.2 and WordPress 6.3
2. Install and activate Heartbeat Control plugin
3. Go to the Heartbeat Control settings
4. Change each of the settings to:  `Allow Heartbeat`, `Disable Heartbeat`, `Modify Heartbeat`. Save settings after each change
5. Check the PHP log

**Expected behavior**
No PHP warnings in the logs, plugin working correctly on the previous PHP/WordPress versions:
1. Disable HeartBeat will disable this feature on specific parts of the website
2. Allow HeartBeat will not limit this feature on specific parts of the website
3. Modify HeartBeat will limit this feature to chosen frequency on specific parts of the website
4. To validate the HeartBeat behaviour, open network tab on specific part of the website and observe the frequency of the following request 
![image](https://github.com/wp-media/heartbeat-control/assets/26767037/ac207273-b448-4dde-a564-595f4641372c)

**Comment by MathieuLamiot** [comment]
@mostafa-hisham Regarding the front-end issue, how does the previous version behaves? To know if it is related to this change?

**Comment by MathieuLamiot** [comment]
@piotrbak Then are we OK with merging & releasing this PR for now?

**Comment by piotrbak** [comment]
@MathieuLamiot Yes, I believe we're good to go
